use_frameworks!

platform :ios, '8.0'

target 'PodTest_Example' do
  pod 'PodTest', :path => '../'

  target 'PodTest_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
